#!/bin/sh
# shellcheck shell=sh disable=SC1090,SC2016
set -eu

PROJECT_CFG_FILE=${1:-${PROJECT_CFG_FILE:-config/project.cfg}}
project_cfg_file=${PROJECT_CFG_FILE}
case "${project_cfg_file}" in
  /* | ./* | ../*) ;;
  *) project_cfg_file="./${project_cfg_file}" ;;
esac
[ -f "${project_cfg_file}" ] || {
  printf 'missing %s; set PROJECT_CFG_FILE to an existing config file\n' "${project_cfg_file}" >&2
  exit 1
}
. "${project_cfg_file}"

project_image=${PROJECT_IMAGE:-kcnotes:local}
release_dir=${RELEASE_INTEGRITY_DIST_DIR:-dist}
release_target=${RELEASE_INTEGRITY_TARGET:-${release_dir}/kcnotes-linux-amd64}
release_name=${RELEASE_INTEGRITY_NAME:-$(basename "${release_target}")}
release_version=${RELEASE_INTEGRITY_VERSION:-local}
enable_sbom=${ENABLE_SBOM:-true}
enable_grype=${ENABLE_GRYPE:-true}
grype_fail_on=${GRYPE_FAIL_ON:-critical}
docker_uid=${DOCKER_UID:-$(id -u)}
docker_gid=${DOCKER_GID:-$(id -g)}
docker_home=${DOCKER_HOME:-/tmp/kcnotes-home}
docker_home_source=${DOCKER_HOME_SOURCE:-$(pwd)/.cache/docker-home}
docker_tmpdir=${DOCKER_TMPDIR:-$(pwd)/.cache/docker-tmp}
mkdir -p "${docker_home_source}" "${docker_tmpdir}" "${release_dir}"

if [ "${enable_grype}" = 'true' ] && [ "${enable_sbom}" != 'true' ]; then
  printf '%s\n' 'ENABLE_GRYPE=true requires ENABLE_SBOM=true because Grype scans the generated SBOM' >&2
  exit 1
fi

printf '\n==> Build kcNotes release binary\n'
sh ./scripts/build.sh "${PROJECT_CFG_FILE}"
docker run --rm --user "${docker_uid}:${docker_gid}" \
  --cap-drop=ALL \
  --security-opt=no-new-privileges:true \
  -e HOME="${docker_home}" \
  -e GOCACHE=/workspace/.cache/go-build \
  -e GOMODCACHE=/workspace/.cache/go-mod \
  -v "${docker_home_source}:${docker_home}" \
  -v "${docker_tmpdir}:/tmp" \
  -v "$(pwd):/workspace" \
  -w /workspace \
  "${project_image}" \
  sh -eu -c "cd src && GOFLAGS='-tags=sqlite_fts5' CGO_ENABLED=1 go build -trimpath -buildvcs=false -ldflags='-s -w' -o ../${release_target} ./cmd/cms"

rm -f "${release_dir}/SECURITY-ANALYSIS.md" "${release_dir}/SHA256SUMS" "${release_dir}/grype-report.txt" "${release_dir}/kcnotes.spdx.json"

if [ "${enable_sbom}" = 'true' ]; then
  syft_image=${DEV_SCAN_SYFT_IMAGE_LOCK}
  case "${syft_image}" in
    *@sha256:*) ;;
    *)
      printf 'DEV_SCAN_SYFT_IMAGE_LOCK must be pinned by digest\n' >&2
      exit 1
      ;;
  esac
  docker run --rm --user "${docker_uid}:${docker_gid}" \
    --cap-drop=ALL \
    --security-opt=no-new-privileges:true \
    -v "$(pwd):/workspace" \
    "${syft_image}" \
    "/workspace/${release_target}" \
    --source-name "${release_name}" \
    --source-version "${release_version}" \
    -o spdx-json >"${release_dir}/kcnotes.spdx.json"
fi

if [ "${enable_grype}" = 'true' ]; then
  grype_image=${DEV_SCAN_GRYPE_IMAGE_LOCK}
  case "${grype_image}" in
    *@sha256:*) ;;
    *)
      printf 'DEV_SCAN_GRYPE_IMAGE_LOCK must be pinned by digest\n' >&2
      exit 1
      ;;
  esac
  docker run --rm --user "${docker_uid}:${docker_gid}" \
    --cap-drop=ALL \
    --security-opt=no-new-privileges:true \
    -v "$(pwd):/workspace" \
    "${grype_image}" \
    "sbom:/workspace/${release_dir}/kcnotes.spdx.json" \
    --fail-on "${grype_fail_on}" \
    -o table >"${release_dir}/grype-report.txt"
fi

{
  printf '# Compliance Report\n\n'
  printf 'This document is generated by `scripts/dist.sh` for kcNotes release artifacts in `%s`.\n\n' "${release_dir}"
  printf '## Scope\n\n'
  printf -- '- Name: `%s`\n' "${release_name}"
  printf -- '- Version: `%s`\n' "${release_version}"
  printf -- '- Target: `%s`\n\n' "${release_target}"
  printf '## Published Release Assets\n\n'
  printf -- '- `%s`\n' "${release_target}"
  printf -- '- `%s/SECURITY-ANALYSIS.md`\n' "${release_dir}"
  printf -- '- `%s/SHA256SUMS`\n' "${release_dir}"
  if [ "${enable_sbom}" = 'true' ]; then
    printf -- '- `%s/kcnotes.spdx.json`\n' "${release_dir}"
  fi
  printf '\n## Controls\n\n'
  printf -- '- Checksums: `%s/SHA256SUMS`\n' "${release_dir}"
  if [ "${enable_sbom}" = 'true' ]; then
    printf -- '- SBOM: `%s/kcnotes.spdx.json`\n' "${release_dir}"
  else
    printf -- '- SBOM: skipped.\n'
  fi
  if [ "${enable_grype}" = 'true' ]; then
    printf -- '- Vulnerability scan: `%s/grype-report.txt`, fail on `%s`.\n' "${release_dir}" "${grype_fail_on}"
  else
    printf -- '- Vulnerability scan: skipped.\n'
  fi
  if [ -f "${release_dir}/grype-report.txt" ]; then
    printf '\n## Vulnerability Scan\n\n```\n'
    cat "${release_dir}/grype-report.txt"
    printf '```\n'
  fi
} >"${release_dir}/SECURITY-ANALYSIS.md"

{
  sha256sum "${release_target}"
  sha256sum "${release_dir}/SECURITY-ANALYSIS.md"
  if [ -f "${release_dir}/kcnotes.spdx.json" ]; then
    sha256sum "${release_dir}/kcnotes.spdx.json"
  fi
} >"${release_dir}/SHA256SUMS"

printf '\n==> Dist summary\n'
printf '%s\n' "Release target: ${release_target}"
